- name: Get OS codename
  command: lsb_release -c
  register: os_codename_raw
  changed_when: false


- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present
    keyring: /usr/share/keyrings/fluentbit-keyring.gpg

- name: Generate repo list
  ansible.builtin.template:
    src: fluentbit.list.j2
    dest: "/etc/apt/sources.list.d/fluentbit.list"
    backup: true


- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install Fluent Bit
  apt:
    name: fluent-bit
    state: present

- name: Ensure Fluent Bit is started and enabled
  systemd:
    name: fluent-bit
    state: started
    enabled: yes

- name: Create configuration directories
  file:
    path: "/etc/fluent-bit/{{ item }}"
    state: directory
  loop:
    - inputs
    - filters
    - outputs

- name: Deploy main Fluent Bit config
  template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf

- name: Deploy input configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/fluent-bit/inputs/{{ item }}"
  loop:
    - loki-input.conf

- name: Deploy filter configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/fluent-bit/filters/{{ item }}"
  loop:
    - loki-filter.conf

- name: Deploy output configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/fluent-bit/outputs/{{ item }}"
  loop:
    - loki-output.conf

- name: Restart Fluent Bit
  systemd:
    name: fluent-bit
    state: restarted
    enabled: yes

